kubevirt/tekton-tasks-operator

- scripts/validate-no-offensive-lang.sh
fix offensive language script
added api/vendor folder to ignored path
```
NONE
```
> fix offensive language script

- tests/tests_suite_test.go
fix e2e tests by enabling feature gate
Fixed wrong CR labels
```NONE
```
> fix e2e tests by enabling feature gate

- scripts/deploy-resources.sh
remove unnecessary command, which sets namespace
```
NONE
```
> remove unnecessary command, which sets namespace

- OWNERS
add 0xFelix as a reviewer
```
NONE
```
> add 0xFelix as a reviewer

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.6.0.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.6.0.yaml
- pkg/operands/version.go
- pkg/tekton-tasks/tekton-tasks.go
bump tekton tasks to version v0.6.0
fix name of task, which will be deployed
```
bump tekton tasks to version v0.6.0
```
> bump tekton tasks to version v0.6.0

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.7.0.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.7.0.yaml
- pkg/operands/version.go
Update tekton tasks manifests to version v0.7.0
```release-note
Update tekton tasks bundle to v0.7.0
```
> Update tekton tasks manifests to version v0.7.0

- README.md
update readme with better description how to deploy TTO
```
NONE
```
> update readme with better description how to deploy TTO

- main.go
disable devel log
log only important events
```
NONE
```
> disable devel log

- config/rbac/role.yaml
- pkg/tekton-tasks/tekton-tasks.go
add update template rbac
```
add update template rbac
```
> add update template rbac

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.8.0.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.8.0.yaml
- pkg/operands/version.go
Update tekton tasks manifests to version v0.8.0
```release-note
Update tekton tasks bundle to v0.8.0
```
> Update tekton tasks manifests to version v0.8.0

- ci-builder/Dockerfile
add new packages to ci builder image
remove code for ansible settings
```
NONE
```
> add new packages to ci builder image

- ci-builder/Dockerfile
add golang and which packages to ci-builder image
```
NONE
```
> add golang and which packages to ci-builder image

- scripts/deploy-resources.sh
Remove 'oc new-project tekton-pipelines' from deployment script
fix rollout command for tekton
```
NONE
```
> deploy openshift version of tekton

- config/rbac/role.yaml
- pkg/tekton-tasks/tekton-tasks.go
This is needed to be able to create Roles which allow creating pods.
See https://github.com/kubevirt/kubevirt-tekton-tasks/pull/140
```release-note
None
```
> tekton-tasks: Add RBAC for creating pods

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.9.0.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.9.0.yaml
- pkg/operands/version.go
Update tekton tasks manifests to version v0.9.0
```release-note
Update tekton tasks bundle to v0.9.0
```
> Update tekton tasks manifests to version v0.9.0

- pkg/tekton-pipelines/tekton-pipelines.go
Fix log message when reverting changes in a pipeline
```release-note
None
```
> Fix log message when reverting changes in a pipeline

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.9.1.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.9.1.yaml
- pkg/operands/version.go
Update tekton tasks manifests to version v0.9.1
```release-note
Update tekton tasks bundle to v0.9.1
```
> Update tekton tasks manifests to version v0.9.1

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.9.2.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.9.2.yaml
- pkg/operands/version.go
Update tekton tasks manifests to version v0.9.2
```release-note
Update tekton tasks bundle to v0.9.2
```
> Update tekton tasks manifests to version v0.9.2

- config/manager/manager.yaml
- data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
fix security constraint for tto container
This PR add adds multiple security context attributes for TTO
```
NONE
```
> fix security constraint for tto container

- config/manager/manager.yaml
- config/rbac/role.yaml
- data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
- data/tekton-pipelines/kubernetes/windows10-customize.yaml
- data/tekton-pipelines/kubernetes/windows10-installer.yaml
- data/tekton-pipelines/okd/windows10-customize.yaml
- data/tekton-pipelines/okd/windows10-installer.yaml
- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.10.0.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.10.0.yaml
- pkg/environment/environment.go
- pkg/environment/environment_test.go
- pkg/operands/version.go
- pkg/tekton-bundle/test-bundle-files/test-pipelines/windows-installer.yaml
- pkg/tekton-bundle/test-bundle-files/test-pipelines/windows-installer2-testyaml
- pkg/tekton-bundle/test-bundle-files/test-tasks/test-tasks.yaml
- pkg/tekton-tasks/tekton-tasks.go
- pkg/tekton-tasks/tekton-tasks_test.go
- scripts/csv-generator.go
- scripts/csv-generator_test.go
Update tekton tasks manifests to version v0.10.0
Update necessary code to onboard new create-data-object task
```
Onboard create-data-object-task
```
> Update tekton tasks manifests to version v0.10.0 

- data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
This reverts the TTO image which was changed by mistake in 612bfdd.
```release-note
None
```
> Revert changes to TTO image in CSV

- pkg/environment/environment.go
Add missing colon in DeafultCreateDataObjectIMG.
Without the colon the image cannot be pulled.
```release-note
None
```
> Add missing colon in DeafultCreateDataObjectIMG

- data/tekton-pipelines/kubernetes/windows10-customize.yaml
- data/tekton-pipelines/kubernetes/windows10-installer.yaml
- data/tekton-pipelines/okd/windows10-customize.yaml
- data/tekton-pipelines/okd/windows10-installer.yaml
Improve reference pipelines
- Do not specify storage size if it can be derived from source
- Move cleanup-vm tasks to finally section so the task is executed even if
the pipeline fails
```release-note
None
```
> Improve reference pipelines

- tests/tests_suite_test.go
enable running tests in different namespace with new env variable TEST_EXISTING_CR_NAMESPACE
```
NONE
```
> enable running tests in different namespace

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.12.0.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.12.0.yaml
- pkg/operands/version.go
Update tekton tasks manifests to version v0.12.0
```release-note
Update tekton tasks bundle to v0.12.0
```
> Update tekton tasks manifests to version v0.12.0

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.12.1.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.12.1.yaml
- pkg/operands/version.go
Update tekton tasks manifests to version v0.12.1
```release-note
Update tekton tasks bundle to v0.12.1
```
> Update tekton tasks manifests to version v0.12.1

- scripts/example-pipelines-test.sh
- scripts/test-files/configmap.yaml
- scripts/test-files/http-server.yaml
- scripts/test-files/win10-dv.yaml
- scripts/test-files/windows10-customize-pipelinerun.yaml
- scripts/test-files/windows10-installer-pipelinerun.yaml
Add script that will run pipeline examples and all manifests of resources that needs to be deployed to run pipelines.
```None
```
> Add test script which runs pipeline examples as presubmit tests.

- tests/tekton-tasks_test.go
fix race condition for test case when multiple ttos are deployed
This commit patches the test, so it can try to check TTO conditions multiple times (every 2 seconds for 60 seconds), because it sometimes can take some time until reconciliation is completed
```
NONE
```
> fix race condition for test case when multiple ttos are deployed

- data/tekton-pipelines/kubernetes/windows10-installer.yaml
- data/tekton-pipelines/okd/windows10-installer.yaml
update winImageDownloadURL param description
added link to official Microsoft site, where user can download windows iso file.
```
update winImageDownloadURL param description
```
> update winImageDownloadURL param description

- Dockerfile
feat: update ubi version in dockerfile
this commit updates ubi version in dockerfile
```
NONE
```
> feat: update ubi version in dockerfile

- config/rbac/role.yaml
- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.9.4.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.9.4.yaml
- pkg/operands/version.go
- pkg/tekton-tasks/tekton-tasks.go
Update tekton tasks manifests to version v0.9.4
**Which issue(s) this PR fixes**:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2142490
```
Update tekton tasks manifests to version v0.9.4
```
> [release-v0.3] Update tekton tasks manifests to version v0.9.4

- data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
fix: add missing permissions to csv
```
NONE
```
> fix: add missing permissions to csv

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.13.0.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.13.0.yaml
- pkg/operands/version.go
- pkg/tekton-tasks/tekton-tasks.go
Update tekton tasks manifests to version v0.13.0
```
Update tekton tasks bundle to v0.13.0
```
> Update tekton tasks manifests to version v0.13.0

- .github/workflows/update-virtio-version.yaml
fix: fix wrong name of main branch
```
NONE
```
> fix: fix wrong name of main branch

- pkg/environment/environment.go
Update virtio image version to v0.58.1
```release-note
Update virtio image version to v0.58.1
```
> Update virtio image version to v0.58.1

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.13.2.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.13.2.yaml
- pkg/operands/version.go
Update tekton tasks manifests to version v0.13.2
```release-note
Update tekton tasks bundle to v0.13.2
```
> Update tekton tasks manifests to version v0.13.2

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.13.3.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.13.3.yaml
- pkg/operands/version.go
Update tekton tasks manifests to version v0.13.3
```release-note
Update tekton tasks bundle to v0.13.3
```
> Update tekton tasks manifests to version v0.13.3

- .snyk
feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
```release-note
NONE
```
> [release-v0.4]feat: add .snyk file

- .snyk
feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
```release-note
NONE
```
> [release-v0.5]feat: add .snyk file
