kubevirt/tekton-tasks-operator

- controllers/tektontasks_controller.go
reenque another reconciliation, when conflict cr occures
this pr changes behaviour when there is an conflict err during cr
update. If there is conflict, reenque new reconciliation cycle
```
NONE
```
> reenque another reconciliation, when conflict cr occures

- config/manager/manager.yaml
- data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
remove runasnonroot attribute from manifests
in kubernetes cluster tto refused to start due to runasnonroot
attribute.
```
NONE
```
> remove runasnonroot attribute from manifests

- tests/tekton-pipelines_test.go
- tests/tekton-tasks_test.go
- tests/tests_suite_test.go
cleanup e2e tests
this PR removes unused functions which left after copying from ssp
operator and simplifies beforeSuite function
```
NONE
```
> cleanup e2e tests

- pkg/tekton-pipelines/tekton-pipelines.go
- pkg/tekton-tasks/tekton-tasks.go
- tests/tekton-pipelines_test.go
- tests/tekton-tasks_test.go
fix deletion of resources, when TTO CR is deleted
During deletion of resources when TTO CR was deleted,
was deleted only one last item from slice. It was caused by fact,
that there was always appended adress of a single item, so in the end,
the slice was full of adresses to a single item.
```
NONE
```
> fix deletion of resources, when TTO CR is deleted

- tests/tekton-tasks_test.go
Add tests to check if tto is not deploying anything when DeployTektonTaskResouces set to false
Fixes: https://github.com/kubevirt/tekton-tasks-operator/issues/4
```NONE
```
> Add tests to check if tto is not deploying anything when DeployTektonTaskResouces set to false

- Dockerfile
- Makefile
- go.mod
- go.sum
bump golang version to 1.18
```
bump golang version to 1.18
```
> bump golang version to 1.18

- ci-builder/Dockerfile
add ci builder image
this image will be used as a base image for openshift ci infrastructure
```
NONE
```
> add ci builder image

- Makefile
- ci-builder/Dockerfile
don't generate manifest during functests
add gcc package to ci builder image
```
NONE
```
> don't generate manifest during functests

- scripts/deploy-resources.sh
To stop this command causing errors in CI tests.
```
+ oc new-project tekton-pipelines
Error from server (Forbidden): You may not request a new project via this API.
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-04-25T09:51:29Z"}
error: failed to execute wrapped command: exit status 1
}
```
```NONE
```
> Remove 'oc new-project tekton-pipelines' from deployment script

- config/manager/manager.yaml
- config/rbac/role.yaml
- controllers/tektontasks_controller.go
- data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
- pkg/environment/environment.go
- pkg/environment/environment_test.go
- pkg/tekton-tasks/tekton-tasks.go
- pkg/tekton-tasks/tekton-tasks_test.go
- scripts/csv-generator.go
- tests/tekton-tasks_test.go
add rest of the tasks to TTO
this PR add three extra tasks - create vm from manifest keys, generate ssh, execute in vm
Fixes: https://github.com/kubevirt/tekton-tasks-operator/issues/10
```
Add create-vm-from-manifest and generate-ssh-keys tasks
```
> add rest of the tasks to TTO

- controllers/tektontasks_controller.go
handle object modified error in initialize steps
not handling object modified error in initialize step caused tests to
be flaky.
```
NONE
```
> handle object modified error in initialize steps

- pkg/tekton-pipelines/tekton-pipelines.go
- pkg/tekton-tasks/tekton-tasks.go
- tests/tekton-pipelines_test.go
tto watches all objects it deploys
Previously tto watched only cluster objects, now it should watch
all objects and revert all user changes
**Which issue(s) this PR fixes**:
Fixes [29](https://github.com/kubevirt/tekton-tasks-operator/issues/29)
```
NONE
```
> tto watches all objects it deploys

- data/tekton-pipelines/okd/windows10-installer.yaml
Hardcoded values instead of the parameters were used by mistake.
```release-note
None
```
> Fix usage of baseDvName and baseDvNamespace parameters

- data/tekton-pipelines/kubernetes/windows10-customize.yaml
There was a reference to a task in runAfter with the wrong task name and
the runStrategy parameter was missing when starting the customize VM.
```release-note
None
```
> Fix windows10-customize pipeline on kubernetes

- config/manager/manager.yaml
- data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
remove prometheus label and port from deploy manifest
currently there is no support planned for prometheus, so to prevent
issues, I am removing prometheus data from deploy manifests
Fixes: https://github.com/kubevirt/tekton-tasks-operator/issues/50, https://github.com/kubevirt/tekton-tasks-operator/issues/49
```
remove prometheus label and port from deploy manifests
```
> remove prometheus label and port from deploy manifest

- data/tekton-pipelines/kubernetes/windows10-installer.yaml
- data/tekton-pipelines/okd/windows10-installer.yaml
- pkg/tekton-pipelines/tekton-pipelines.go
- tests/tekton-pipelines_test.go
- tests/tekton-tasks_test.go
add pipeline service account into installer pipeline
Tekton operator does not deploy pipeline SA in ^openshift|kube
namespaces. This PR deploys it if tekton operator is deployed in namespace which passes regex
```
Deploy pipeline serviceAccount in the same namespace as tekton-tasks operator
```
> add pipeline service account into installer pipeline

- pkg/tekton-pipelines/tekton-pipelines.go
update only labels and annotations in serviceAccounts in pipelines
```
NONE
```
> update only labels and annotations in serviceAccounts in pipelines

- data/tekton-pipelines/okd/windows10-installer.yaml
- pkg/tekton-pipelines/tekton-pipelines.go
add cluster role in pipelines
when pipeline is deployed in ^openshift|kube namespace
it requires more permissions to run
```
Deploy extra cluster role, when deployed in ^openshift|kube namespace
```
> add cluster role in pipelines when deployed in ^openshift|kube namespace

- pkg/tekton-pipelines/tekton-pipelines.go
fix deploying of windows10-pipelines clusterrole
```
NONE
```
> fix deploying of windows10-pipelines clusterrole

- scripts/deploy-resources.sh
Add deployment of common templates to deploy-resources.sh
Script `deploy-resources.sh` will now deploy common templates.
```NONE
```
> Add deployment of common templates to deploy-resources.sh

- scripts/deploy-resources.sh
- scripts/ssp-sample.yaml
Add deployment of SSP operator that is needed to run example pipelines to deployment script. 
```None
```
> Add deployment of SSP to deployment script, that is needed for run of example pipelines

- data/tekton-pipelines/kubernetes/windows10-installer.yaml
This PR adds permissions to SA that is used by windows10-installer pipeline that were needed to run pipeline without error.
**Which issue(s) this PR fixes** :
Fixes https://github.com/kubevirt/kubevirt-tekton-tasks/issues/163
```None
```
> Add permissions to SA used by windows10-installer pipeline

- tests/tekton-pipelines_test.go
- tests/tekton-tasks_test.go
This PR edits tests, so they will pass when `windows10-pipelines` clusterRole and roleBinding is created.
```None
```
> Edit tests for clusterRole and roleBinding creation

- pkg/tekton-pipelines/tekton-pipelines.go
This PR will allow pipeline to create clusterRole and roleBinding that are needed to run it.
```None
```
> Delete condition that blocks creation of clusterRole and roleBinding

- data/tekton-pipelines/okd/windows10-installer.yaml
This PR adds permissions to SA in kubevirt-os-images namespace and removes dependency on `modify-data-object-task`, so pipeline and clusterTasks can be created in parallel.
```None
```
> Add permissions to pipeline SA in kubevirt-os-images namespace

- data/tekton-pipelines/okd/windows10-customize.yaml
- data/tekton-pipelines/okd/windows10-installer.yaml
This PR adds new functionality of tekton tasks that allows us to delete resources like data volumes and templates to the example pipelines. Example pipelines will now delete resources that are created during the run of pipelines, but they are not part of pipelines results. 
This PR also sets allowReplace to the windows-installer pipeline base datavolume so it can be run repeatedly.
<!--  Write your release note:
```None
```
> Delete resources that are created during the run of example pipelines and set allowReplace of base datavolume.

- data/tekton-pipelines/okd/windows10-customize.yaml
- data/tekton-pipelines/okd/windows10-installer.yaml
This PR adds annotations to example pipelines datavolumes that will not allow CDI gabage collector delete these datavolumes.
```None
```
> Add annotations to example pipelines datavolumes.

- .github/workflows/release.yaml
update golang version to 1.18 in github actions
```
NONE
```
> update golang version to 1.18 in github actions

- Dockerfile
add command USER 1001 to dockerfile to prevent issues while running on vanilla k8s
if the image used does not define a USER ID you will check the following error:"container has runAsNonRoot and image will run as root. This Fix sets the USER command in dockerfile
```
NONE
```
> add command USER 1001 to dockerfile 

- data/tekton-pipelines/okd/windows10-installer.yaml
This PR adds permissions to modify-data-object-task service account, that are required by example pipelines to run them.
Fixes #
> Add permissions to modify-data-object-task service account

- controllers/tektontasks_controller.go
- tests/tekton-tasks_test.go
- tests/tests_suite_test.go
This PR implements check if there are more CRs deployed. When there is more than one CR the TTO status is set to Degraded, reconcile loop stops and error log is generated.
```None
```
> Add functionality that will check if multiple CRs are deployed

- ci-builder/Dockerfile
golang was updated to 1.19
fedora was updated to fixed version, to prevent future issues with older releases of tto built on newest fedora.
```
NONE
```
> update golang and fedora version in ci-builder dockerfile

- data/tekton-pipelines/okd/windows10-installer.yaml
add pipeline serviceaccount to testing windows10 pipeline
This will fix the issue when pipeline is created via UI and has Insufficient permissions to create datavolume 
```
NONE
```
> add pipeline serviceaccount to testing windows10 pipeline

- data/tekton-pipelines/okd/windows10-installer.yaml
add missing delete template permission to win 10 installer pipeline
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2152094
```
NONE
```
> add missing delete template permission to win 10 installer pipeline

- tests/tekton-tasks_test.go
fix: fix flaky feature gate tests
When user disables deploy feature gate, tests will wait until all resources are deleted. This is wrong, beceause tto will not delete any resources, but it will just disable reconciliation. This patch updates behaviour of the test, to try if the operator is still reconciling the resources
```
NONE
```
> fix: fix flaky feature gate tests

- .github/workflows/update-virtio-version.yaml
- config/manager/manager.yaml
- data/olm-catalog/tekton-tasks-operator.clusterserviceversion.yaml
- pkg/environment/environment.go
- pkg/environment/environment_test.go
- pkg/tekton-pipelines/tekton-pipelines.go
- scripts/csv-generator.go
- scripts/csv-generator_test.go
fix: add new VIRTIO_IMG env varible to operator
with this new env variable, we will be able to use newest virtio container img available in example pipelines
**Which issue(s) this PR fixes**:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2155796
```
NONE
```
> fix: add new VIRTIO_IMG env varible to operator

- scripts/example-pipelines-test.sh
fix: switch to ssd storageClass in example pipeline tests
The ocp 4.13 is using by default slow storageclass. This might cause timeouts. This commit changes deafult storageclass to ssd storageclass
```
NONE
```
> fix: switch to ssd storageClass in example pipeline tests

- data/tekton-pipelines/kubernetes/windows-efi-installer.yaml
- data/tekton-pipelines/kubernetes/windows2022-installer-configmaps.yaml
- data/tekton-pipelines/okd/windows-customize.yaml
- data/tekton-pipelines/okd/windows-efi-installer.yaml
- data/tekton-pipelines/okd/windows2022-installer-configmaps.yaml
- scripts/test-files/windows2022-customize-pipelinerun.yaml
- scripts/test-files/windows2022-dv.yaml
- scripts/test-files/windows2022-installer-pipelinerun.yaml
Add windows server 2022 autounattend config map
This commit adds new configmap for windows server 2022 and renames
windows11-installer pipeline to windows-efi-installer pipeline.
With this change user can install other windows which requires efi +
secure boot with single pipeline.
```
Add windows server 2022 autounattend config map
```
> feat: Add windows server 2022 autounattend config map

- data/tekton-tasks/kubernetes/kubevirt-tekton-tasks-kubernetes-v0.13.1.yaml
- data/tekton-tasks/okd/kubevirt-tekton-tasks-okd-v0.13.1.yaml
- pkg/operands/version.go
- scripts/deploy-resources.sh
Update tekton tasks manifests to version v0.13.1
```release-note
Update tekton tasks bundle to v0.13.1
```
> Update tekton tasks manifests to version v0.13.1

- data/tekton-pipelines/kubernetes/windows-efi-installer-pipeline.yaml
- data/tekton-pipelines/okd/windows-efi-installer-pipeline.yaml
fix: generate imported iso name
The imported DV is mounted to modify-windows-iso task. When user tries to rerun the efi pipeline, pipeline will fail, because PVC already exists even allowReplaceISODV param is set to true. This is because already mounted PVC can't be deleted and kubernetes sets status of PVC to terminating (but the pvc stays in cluster until modify-windows-iso pod exists) when the task tries to delete it. This PR update pipeline to create new DV/PVC for each pipelineRun and then deletes it. The PVC will then be deleted when user deletes pipelineRun.
/hold
waits for https://github.com/kubevirt/kubevirt-tekton-tasks/pull/225
```
NONE
```
> fix: generate imported iso name

- data/tekton-pipelines/kubernetes/windows-customize-configmaps.yaml
- data/tekton-pipelines/kubernetes/windows-customize-pipeline.yaml
- data/tekton-pipelines/okd/windows-customize-configmaps.yaml
- data/tekton-pipelines/okd/windows-customize-pipeline.yaml
- scripts/test-files/windows2k22-customize-pipelinerun.yaml
feat: switch default configmap for windows-customize pipeline
This PR switch default configmap for windows-customize pipeline from windows-sqlserver to windows-vs-code. This change is done, because it makes more sense to install vs-code to windows10/11 than sql server. The windows 2k22 can still use vs-code or sql server config map
```
switch default configmap (from sql server to vs code) for windows-customize pipeline
```
> feat: switch default configmap for windows-customize pipeline

- scripts/deploy-resources.sh
- scripts/example-pipelines-test.sh
fix: revert back the hardcoded version of kubevirt for tests
fix: remove TSC labels from worker nodes in e2e tests
Latest kubevirt version introduced tsc node selectors for windows vms. This is causing problems during scheduling of windows VM, which are in pending state, due to different tsc labels on nodes. Currently there is no easy fix in kubevirt, because it would break migration flow. Due to that, we have to disable node-labeller and remove the tsc labels from nodes, so virt-controller can schedule the VMs on more nodes. This approach will break migration flow, but in our tests we do not test it.
```
NONE
```
> fix: revert back the hardcoded version of kubevirt for tests

- pkg/environment/environment.go
- pkg/environment/environment_test.go
fix: wrong modify-data-object env variable name
This PR fixes wrong MODIFY_DATAOBJECT_IMG env variable name with correct MODIFY_DATA_OBJECT_IMG.
```
fix: wrong modify-data-object env variable name
```
> fix: wrong modify-data-object env variable name

- data/tekton-pipelines/okd/windows-customize-configmaps.yaml
fix: change name of ipv4 subinterface
It looks like qemu changes ipv4 subinterface across versions (e.g.
https://forum.proxmox.com/threads/no-network-adapter-in-fresh-windows-server-after-upgrade-to-proxmox-7.92094/page-2#post-404218).
This PR updates name of ipv4 subinterface to be retrieved automatically
from available subinterfaces.
```
NONE
```
> fix: change name of ipv4 subinterface

- README.md
BREAKING CHANGE: This project is deprecated
This project is now deprecated and should not be used. Use SSP operator instead - github.com/kubevirt/ssp-operator
```
This project is now deprecated
```
> BREAKING CHANGE: This project is deprecated
